tms/tms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('travel/', include('travel.urls')),
    path('user/notif/', include('notif.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tms/travel/urls.py
from django.urls import path
from . import views

app_name = 'travel'

urlpatterns = [

	path('', views.home, name='home'),
	path('addtrip/', views.addtrip, name='addtrip'),
	path('deltrip/tripid=<tripid>', views.deltrip, name='deltrip'),
	path('updtrip/tripid=<tripid>', views.updtrip, name='updtrip'),
	path('updhotel/tripid=<tripid>', views.updhotel, name='updhotel'),
	path('upditinerary/tripid=<tripid>', views.upditinerary, name='upditinerary'),
	path('updlocation/tripid=<tripid>', views.updlocation, name='updlocation'),
	path('updtransport/tripid=<tripid>', views.updtransport, name='updtransport'),
	path('deltransport/trid=<tr_id>', views.deltransport, name='deltransport'),
	path('delitinerary/itineraryid=<itinerarybookid>', views.delitinerary, name='delitinerary'),
	path('dellocation/tripid=<tripid>/locationid=<location_id>', views.dellocation, name='dellocation'),
	path('delhotel/hotelid=<hotelbookid>', views.delhotel, name='delhotel'),
	path('details/tripid=<tripid>', views.details, name='details')

]

tms/travel/models.py
from django.db import models

# Create your models here.

tms/travel/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import connection, transaction
from django.db import connections
from datetime import datetime,timedelta

from notif.views import *

from django.core.files.storage import FileSystemStorage
from django.conf import settings
from PIL import Image
from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent


import json
# Create your views here.
from django.http import HttpResponse

def home(request):
	if 'customer_id' in request.session:
		note_count = notecount(request.session['customer_id'])
		with connection.cursor() as cursor:
			cursor.execute("SELECT first_name from customer WHERE customer_id = %s", [request.session['customer_id']])
			name = cursor.fetchone()
		with connection.cursor() as cursor:
			cursor.execute("SELECT title, description,trip_id from trips WHERE customer_id = %s and start_date <= %s and end_date >= %s", [request.session['customer_id'],datetime.now().date(),datetime.now().date()])
			rows = cursor.fetchall()
		with connection.cursor() as cursor:
			cursor.execute("SELECT title, description,trip_id from trips WHERE customer_id = %s and start_date > %s" , [request.session['customer_id'],datetime.now().date()])
			upcoming_rows = cursor.fetchall()
		with connection.cursor() as cursor:
			cursor.execute("SELECT title, description,trip_id from trips WHERE customer_id = %s and end_date < %s" , [request.session['customer_id'],datetime.now().date()])
			past_rows = cursor.fetchall()
		
		log_in = True
		cnt_list = [1,1,1]
		if len(rows) == 0:
			cnt_list[0] = 0
		if len(upcoming_rows) == 0:
			cnt_list[1] = 0
		if len(past_rows) == 0:
			cnt_list[2] = 0
		return render(request, 'travel/home.html', {'rows':rows,'log_in':log_in,'first_name':name[0],'upcoming_rows':upcoming_rows,'past_rows':past_rows,'cnt_list':cnt_list,'note_count':note_count})
	return redirect('user:login')

def addtrip(request):
	if 'customer_id' in request.session:
		note_count = notecount(request.session['customer_id'])
		with connection.cursor() as cursor:
			cursor.execute("SELECT first_name from customer WHERE customer_id = %s", [request.session['customer_id']])
			name = cursor.fetchone()
		if request.method == "POST":
			title = request.POST["title"]
			description = request.POST["description"]
			drive_link = request.POST["drive_link"]
			start_date = request.POST["start_date"]
			end_date = request.POST["end_date"]
			if end_date < str(datetime.now().date()):
				messages.error(request, f'Trip cannot be added as it already ended!')
				return redirect('travel:addtrip')
			if end_date < start_date : 
				messages.error(request, f'Trip cannot be added as end date cannot be before start date!')
				return redirect('travel:addtrip')
			cursor = connections['default'].cursor()
			cursor.execute("INSERT INTO trips(title, description, drive_link, start_date, end_date, customer_id)  VALUES (%s, %s, %s,%s,%s,%s)",
					   [title, description, drive_link, start_date, end_date, request.session['customer_id']])
			with connection.cursor() as cursor:
				cursor.execute("SELECT max(trip_id) from trips WHERE customer_id = %s", [request.session['customer_id']])
				row = cursor.fetchone()
			timing = datetime.strptime(start_date,'%Y-%m-%d')
			timing -= timedelta(days=2) 
			cursor = connections['default'].cursor()
			cursor.execute("INSERT INTO notifications(trip_id,category,time_)  VALUES (%s,%s,%s)",
						[row[0],0,timing])
			timing = datetime.strptime(start_date,'%Y-%m-%d')
			timing -= timedelta(hours=12) 
			cursor = connections['default'].cursor()
			cursor.execute("INSERT INTO notifications(trip_id,category,time_)  VALUES (%s,%s,%s)",
						[row[0],1,timing])
			return redirect('travel:updtrip',tripid=row[0])
		else:
			return render(request, 'travel/addtrip.html',{'log_in':True,'first_name':name[0],'note_count':note_count})
	return redirect('user:login')

def deltrip(request,tripid):
	if 'customer_id' in request.session:
		cursor = connections['default'].cursor()
		cursor.execute("DELETE from trips WHERE trip_id = %s", [tripid])
		return redirect('travel:home')
	return redirect('user:login')


def updtrip(request,tripid):
	if 'customer_id' in request.session:
		note_count = notecount(request.session['customer_id'])
		with connection.cursor() as cursor:
			cursor.execute("SELECT first_name from customer WHERE customer_id = %s", [request.session['customer_id']])
			name = cursor.fetchone()
		if request.method == 'POST':
			title = request.POST["title"]
			description = request.POST["description"]
			drive_link = request.POST["drive_link"]
			start_date = request.POST["start_date"]
			end_date = request.POST["end_date"]
			cursor = connections['default'].cursor()
			if start_date>end_date :
				messages.error(request, f'Trip cannot be added as end date cannot be before start date!')
				return redirect('travel:updtrip',tripid=tripid)
			if end_date < str(datetime.now().date()) :
				messages.error(request, f'Trip cannot be added as it already ended!')
				return redirect('travel:updtrip',tripid=tripid) 
			cursor.execute("UPDATE trips SET title = %s, description = %s, drive_link = %s, start_date = %s, end_date = %s WHERE trip_id = %s",
					[title, description, drive_link, start_date, end_date, tripid])

		with connection.cursor() as cursor:
			cursor.execute("SELECT * from trips WHERE trip_id = %s", [tripid])
			row = cursor.fetchone()
			cursor.execute("SELECT * from location ")
			location_options = cursor.fetchall()
			cursor.execute("SELECT location_id,place_name from location natural join travels WHERE trip_id = %s", [tripid])
			row1 = cursor.fetchall()
			location_options = [i for i in location_options if i not in row1]
			cursor.execute("SELECT hotelbookid,name,cost,checkin,checkout,booking_doc,id_card from hotel natural join hotelbooking WHERE trip_id= %s", [tripid])
			row4 = cursor.fetchall()
			cursor.execute("SELECT itinerarybookid,name,title,ticket_price,visit_time,itinerarybooking.address from itinerarybooking, itinerary WHERE itinerarybooking.itineraryid=itinerary.itineraryid and trip_id= %s", [tripid])
			row5 = cursor.fetchall()
			cursor.execute("SELECT tr_id,type,trans_name,departure,arrival,from_loc,to_loc,cost,ticket from transportbooking WHERE trip_id= %s", [tripid])
			row6 = cursor.fetchall()
			cursor.execute("SELECT hotelid,name,rating from hotel natural join travels WHERE travels.location_id=hotel.location_id and trip_id= %s", [tripid])
			row2 = cursor.fetchall()
			cursor.execute("SELECT itineraryid,name,rating from travels natural join itinerary WHERE travels.location_id=itinerary.location_id and itineraryid != %s and trip_id= %s", [1,tripid])
			row3 = cursor.fetchall()

		j = 1
		row1f = []
		for i in row1:
			k = list(i)
			k.append(j)
			row1f.append(k)
			j += 1

		j = 1
		row4f = []
		for i in row4:
			k = list(i)
			k.append(j)
			row4f.append(k)
			j += 1

		j = 1
		row5f = []
		for i in row5:
			k = list(i)
			k.append(j)
			row5f.append(k)
			j += 1

		j = 1
		row6f = []
		for i in row6:
			k = list(i)
			k.append(j)
			row6f.append(k)
			j += 1

		context = {
			'log_in': True,
			'first_name': name[0],
			'title': row[2],
			'description': row[3],
			'drive_link': row[4],
			'start_date': str(row[5]),
			'end_date': str(row[6]),
			'locations': location_options,
			'locationlist' : row1f,
			'hotellist' : row4f,
			'itinerarylist' : row5f,
			'transportlist' : row6f,
			'hotels':row2,
			'itinerary': row3,
			'tripid': tripid,
			'note_count':note_count
		}
		return render(request, 'travel/updtrip.html', context)
	return redirect('user:login')



def updtransport(request,tripid):
	if 'customer_id' in request.session:
		if  request.method == "POST":
			type_t = request.POST["type"]
			from_loc = request.POST["from"]
			to_loc = request.POST["to"]
			trans_name = request.POST["trans_name"]
			cost = request.POST["cost"]
			doc = request.FILES
			if 'document_image' in request.FILES:
				doc_name = doc['document_image']
			else:
				doc_name = False
			if request.method == 'POST' and doc_name:
				image = request.FILES['document_image']
				fs = FileSystemStorage()
				image_name = fs.save(image.name, image)
				uploaded_image_url = fs.url(image_name)
			departure = request.POST["departure"]
			arrival = request.POST["arrival"]
			if arrival < departure:
				messages.error(request, f' You cannot arrive before departing!!')
			elif arrival >= departure and doc_name==False:
				cursor = connections['default'].cursor()
				cursor.execute("INSERT INTO transportbooking(type,from_loc,to_loc,trans_name,cost,departure,arrival,trip_id)  VALUES (%s, %s, %s,%s,%s,%s,%s,%s)",
						[type_t,from_loc,to_loc,trans_name,cost,departure,arrival, tripid])
				date_time_obj = datetime.strptime(departure, '%Y-%m-%dT%H:%M')
				timing = date_time_obj - timedelta(hours=1) 
				cursor = connections['default'].cursor()
				cursor.execute("INSERT INTO notifications(trip_id,category,time_)  VALUES (%s,%s,%s)",[tripid,2,timing])
			elif arrival >= departure and doc_name:
				cursor = connections['default'].cursor()
				cursor.execute("INSERT INTO transportbooking(type,from_loc,to_loc,trans_name,cost,departure,arrival,trip_id,ticket)  VALUES (%s,%s, %s, %s,%s,%s,%s,%s,%s)",
						[type_t,from_loc,to_loc,trans_name,cost,departure,arrival, tripid,uploaded_image_url])
				date_time_obj = datetime.strptime(departure, '%Y-%m-%dT%H:%M')
				timing = date_time_obj - timedelta(hours=1) 
				cursor = connections['default'].cursor()
				cursor.execute("INSERT INTO notifications(trip_id,category,time_)  VALUES (%s,%s,%s)",[tripid,2,timing])

		return redirect('travel:updtrip',tripid=tripid)
	return redirect('user:login')





def updlocation(request,tripid):
	if 'customer_id' in request.session:
		if request.method == "POST":
			location_id = request.POST["location_id"]

			cursor = connections['default'].cursor()

tms/travel/templates/travel/addtrip.html
{% extends 'user/base.html' %}

{% block content %}
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <!-- <form class="" method="POST" action="{% url 'travel:addtrip' %}" >
        {% csrf_token %}
        <div class="bg-grey-lighter min-h-screen flex flex-col">
            <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
                <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
                    <h1 class="mb-8 text-3xl text-center">Trip Details</h1>
                    <input
                            type="text"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="title"
                            placeholder="Title" />

                    <input
                            type="text"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="description"
                            placeholder="Description" />
                    <input
                            type="text"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="drive_link" 
                            placeholder="Drive Link" />
                    <input
                            type="date"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="start_date"
                            placeholder="Enter a tentative Start Date" />
                    <input
                            type="date"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="end_date"
                            placeholder="Enter a tentative End Date" />
                    <button
                            type="submit"
                            class="text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded "
                    >Add trip</button>
                </div>
            </div>
        </div>
    </form> -->
    <div class="container"></div>
    <div class="signup-form">
        <form class="form-horizontal" method="POST" action="{% url 'travel:addtrip' %}" >
            {% csrf_token %}              
            <div class="row">
                <div class="col-8 offset-4">
                    <h2>Trip Details</h2>
                </div>	
              </div>	
            <div class="form-group row">
                <label class="col-form-label col-4">Title</label>
                <div class="col-8">
                    <input type="text" class="form-control" name="title" required="required" >
                </div>        	
            </div>
            <div class="form-group row">
                <label class="col-form-label col-4">Description</label>
                <div class="col-8">
                    <input type="text" class="form-control" name="description" required="required">
                </div>        	
            </div>
            <div class="form-group row">
                <label class="col-form-label col-4">Drive Link</label>
                <div class="col-8">
                    <input type="text" class="form-control" name="drive_link" >
                </div>        	
            </div>
            <div class="form-group row">
                <label class="col-form-label col-4">Start Date</label>
                <div class="col-8">
                    <input type="date" class="form-control" name="start_date"  required="required">
                </div>          	
            </div>
            <div class="form-group row">
                <label class="col-form-label col-4">End Date</label>
                <div class="col-8">
                    <input type="date" class="form-control" name="end_date"  required="required">
                </div>          	
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    <button type="submit" class="btn btn-primary btn-lg">Add Trips</button>
                </div>  
            </div>		      
        </form>
    </div>
{% endblock %}

tms/travel/templates/travel/home.html
{% extends 'user/base.html' %}

{% block content %}
<!-- <div class="container-fluid  text-center">
   <h1 class="text-center">Your Trips</h1> -->
   <div class=" container text-center">
      <div class="panel panel-default">
         <div class="panel-heading">
            <h2>Add New Trips</h2>
         </div>
         <div class="panel-body">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 container_foto ">
               <div class="ver_mas text-center">
                  <a href="{% url 'travel:addtrip' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
               </div>
               <article class="text-left">
                  <h2>WANNA ADD<br> NEW TRIP</h2>
                  <h4>Lets Start A New Journey!!</h4>
               </article>
               <img src="https://img-aws.ehowcdn.com/400x400/ds-img.studiod.com/Half_Dome_from_Glacier_Point0_1.jpg"
                  alt="">
            </div>
         </div>
      </div>
      {% if cnt_list.0 %}
      <div class="panel panel-default">
         <div class="panel-heading">
            <h2>Ongoing Trips</h2>
         </div>
         <div class="panel-body">
            {% for row in rows %}
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 container_foto ">
               <div class="ver_mas text-center">
                  <a href="{% url 'travel:details' row.2 %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
               </div>
               <article class="text-left">
                  <h2>{{row.0}}</h2>
                  <h4>{{row.1}}</h4>
               </article>
               <img src="https://pbs.twimg.com/profile_images/781518570018648065/HcvZhTVn_400x400.jpg" alt="">
            </div>
            {% endfor %}
         </div>
      </div>
      {% endif %}
      {% if cnt_list.1 %}
      <div class="panel panel-default">
         <div class="panel-heading">
            <h2>Upcoming Trips</h2>
         </div>
         <div class="panel-body">
            {% for row in upcoming_rows %}
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 container_foto ">
               <div class="ver_mas text-center">
                  <a href="{% url 'travel:details' row.2 %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
               </div>
               <article class="text-left">
                  <h2>{{row.0}}</h2>
                  <h4>{{row.1}}</h4>
               </article>
               <img src="https://pbs.twimg.com/profile_images/781518570018648065/HcvZhTVn_400x400.jpg" alt="">
            </div>
            {% endfor %}
         </div>
      </div>
      {% endif %}
      {% if cnt_list.2 %}
      <div class="panel panel-default">
         <div class="panel-heading">
            <h2>Past Trips</h2>
         </div>
         <div class="panel-body">
            {% for row in past_rows %}
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 container_foto ">
               <div class="ver_mas text-center">
                  <a href="{% url 'travel:details' row.2 %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
               </div>
               <article class="text-left">
                  <h2>{{row.0}}</h2>
                  <h4>{{row.1}}</h4>
               </article>
               <img src="https://pbs.twimg.com/profile_images/781518570018648065/HcvZhTVn_400x400.jpg" alt="">
            </div>
            {% endfor %}
         </div>
      </div>
      {% endif %}

      <!-- </div> -->
      <!-- </div> -->
      {% endblock %}