labt/labt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('post/', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labt/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [

	path('', views.home, name='home'),
	path('create/',views.create, name='create'),
	path('join/postid=<post_id>',views.join, name ='join'),
	path('joinrequest/',views.joinrequest, name ='joinrequest'),
	path('joinapprove/<request_id>',views.joinapprove, name ='joinapprove'),
	path('mrequest/',views.mrequest, name='mrequest'),
	path('approve/<post_id>',views.approve, name='approve')

]

labt/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [

	path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.register, name='signup'),
    path('profile/', views.profile, name='profile')

]

labt/user/models.py
from django.db import models

# Create your models here.

labt/user/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db import connection, transaction
from django.db import connections
from datetime import datetime

# Create your views here.
from django.http import HttpResponse

# from django.core.files.storage import FileSystemStorage
# from django.conf import settings
# from PIL import Image
# from pathlib import Path
# BASE_DIR = Path(__file__).resolve().parent.parent

def register(request):
	if 'customer_id' in request.session:
		messages.error(request, f'Please Logout First')
		return redirect('user:profile')
	context = {}
	if request.method == 'POST':
		first_name = request.POST["first_name"]
		last_name = request.POST["last_name"]
		gender = request.POST["gender"]
		address = request.POST["address"]
		mobile = request.POST["mobile"] 
		emailid = request.POST["email"]
		password = request.POST["password"]
		confirm_password = request.POST["confirm_password"]
		date_of_birth = request.POST["dob"]
		passkey = request.POST["passkey"]
		moderator = 0
		if passkey != "" and passkey != "mod":
			messages.error(request, f'Wrong moderator passkey')
			return redirect('user:signup')
		elif passkey == "mod":
			moderator = 1
		if len(mobile) != 10:
			messages.error(request, f'Mobile No. should be of exactly 10 digits')
			return redirect('user:signup')
		if password != confirm_password:
			messages.error(request, f'Password and Confirm Password do not match')
			context = {
				'log_in': False
			}
			return redirect('user:signup')
		cursor = connections['default'].cursor()
		try:
			cursor.execute("INSERT INTO customer(first_name, last_name, gender, address, mobile, emailid, password, dob, moderator)  VALUES (%s, %s, %s,%s,%s,%s,%s,%s,%s)",
					   [first_name, last_name, gender, address, mobile, emailid, password, date_of_birth,moderator])
		except Exception as error:
			error_str = str(error)
			if 'customer_chk_2' in error_str:
				messages.error(request, f'Mobile No. in Wrong Format')
			if 'customer_chk_3' in error_str:
				messages.error(request, f'Email ID in Wrong Format')
			return redirect('user:signup')
		return redirect('user:login')
	else:
		return render(request, 'user/register.html',{'log_in':False,'mod':False})


def login(request):
	if 'customer_id' in request.session:
		messages.error(request, f'Please Logout First')
		return redirect('user:profile')
	context = {}
	if request.method == 'POST':
		emailid = request.POST["email"]
		password = request.POST["password"]
		with connection.cursor() as cursor:
			cursor.execute("SELECT * from customer WHERE emailid = %s AND password = %s", [emailid, password])
			row = cursor.fetchone()
			if row is None:
				messages.error(request, f'User Not found! If you are new you may register first.')
				context = {
					'log_in': False
				}
				return render(request, 'user/login.html', {'log_in': False,'mod':False})

			request.session['customer_id'] = row[0]  
			return redirect('user:profile')

	else:
		return render(request, 'user/login.html',{'log_in': False,'mod':False})


def logout(request):
	if 'customer_id' in request.session:
		del request.session['customer_id']
		messages.success(request, f'Successfully Logged Out!!')
		return redirect('user:login')
	else:
		return redirect('user:login')

def profile(request):
	context = {}
	if 'customer_id' in request.session:
		if request.method == 'POST':
			first_name = request.POST["first_name"]
			last_name = request.POST["last_name"]
			emailid = request.POST["email"]
			address = request.POST["address"]
			mobile = request.POST["mobile"]
			#gender = request.POST["gender"]
			curr_password=request.POST["curr_password"]
			new_password=request.POST["new_password"]
			confirm_password=request.POST["confirm_password"]
			if len(mobile) != 10:
				messages.error(request, f'Mobile No. should be of exactly 10 digits')
				return redirect('user:profile')

			
			cursor = connections['default'].cursor()
			cursor.execute("SELECT * from customer WHERE customer_id = %s", [request.session['customer_id']])
			row = cursor.fetchone()
			if curr_password=="" and new_password=="" and confirm_password=="":
				curr_password=row[7]
				new_password=row[7]
				confirm_password=row[7]
			if curr_password!=row[7] :
				messages.error(request, f'Current Password incorrect')
				return redirect('user:profile')
			if new_password != confirm_password:
				messages.error(request, f'Password and Confirm Password do not match')
				return redirect('user:profile')
			try:
				cursor.execute(
					"UPDATE customer SET first_name = %s, last_name = %s, emailid = %s, mobile = %s, address = %s,password=%s WHERE customer_id = %s",
					[first_name, last_name, emailid, mobile, address,new_password,request.session['customer_id']])
				messages.success(request,f'Update Successful!!')
			except Exception as error:
				error_str = str(error)
				if 'customer_chk_2' in error_str:
					messages.error(request, f'Mobile No. in Wrong Format')
				if 'customer_chk_3' in error_str:
					messages.error(request, f'Email ID in Wrong Format')
				return redirect('user:profile')

		# print(first_name, last_name, email)
		with connection.cursor() as cursor:
			cursor.execute("SELECT * from customer WHERE customer_id = %s", [request.session['customer_id']])
			row = cursor.fetchone()
		context = {
			'log_in': True,
			'first_name': row[1],
			'last_name': row[2],
			'gender': row[3],
			'address': row[4],
			'mobile': row[5],
			'email': row[6],
			'curr_password' : "",
			'dob': row[8],
			'mod': row[9]
		}
		return render(request, 'user/profile.html', context)
	return redirect('user:login')

labt/user/templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<html>
<head>
   <!-- Required meta tags -->
    <meta charset="utf-8">
    {% if log_in %}
      <title>{{first_name}}</title>
    {% else %}
      <title>Hollab</title>
    {% endif %}
    <link rel="shortcut icon" href="{% static 'base/h.jpeg' %}"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  
</head>
{% if log_in %}
  <body style=" background-color: white;">
  {% else %}
    <body style="background-image: url('{% static 'base/back.jpg' %}');">
  {% endif %}

<nav class="navbar navbar-inverse" style="background-color: #111; z-index: 1000;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <div class="navbar-header"><img src="{% static 'base/h.jpeg' %}" alt="Title" height="49"></div>
      <a class="navbar-brand" style="color: #FA90CF; font-size: 2.5rem; " href="{% url 'user:login' %}">ollab</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      {% if log_in %}
        <ul class="nav navbar-nav">
          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'post:home' %}"><i class="fa fa-home icon fa-lg" aria-hidden="true"></i> {{first_name}}</a></li>
          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'post:create' %}">Create Post</a></li>

          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'post:joinrequest' %}">Join Requests</a></li>
          {% if mod %}
          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'post:mrequest' %}">Approval Requests</a></li>
          {% endif %}
          
        </ul>
      {% endif %}
      <ul class="nav navbar-nav navbar-right">
        {% if log_in %}
          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'user:profile' %}"><i class="fa fa-user-circle-o icon fa-lg" aria-hidden="true"></i> Profile</a></li>
          <li><a style="color: #FA90CF;font-size: 1.5rem;" href="{% url 'user:logout' %}">Logout <i class="fa fa-sign-out icon fa-lg" aria-hidden="true"></i></a></li>
        {% else %}
          <li><a style="color: #FA90CF; font-size: 1.5rem;" href="{% url 'user:login' %}"><i class="fa fa-sign-in icon fa-lg" aria-hidden="true"></i> Login</a></li>
          <li><a style="color: #FA90CF; font-size: 1.5rem;" href="{% url 'user:signup' %}"><i class="fa fa-user-plus icon fa-lg" aria-hidden="true"></i> Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
    <!-- <main role="main" class="container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
         
    </main> -->

    <div class="row justify-content-center">
      <div class="col-md-10">
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }} container" style="text-align: center;">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          
      </div>
      
    </div>
    {% block content %}{% endblock %}

    <br>
    <br>
    <br>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    {% block javascript %}
    {% endblock javascript %}
</body>
</html>

labt/user/templates/user/login.html
{% extends 'user/base.html' %}

{% block content %}
{% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <!-- <form class="" method="POST" action="{% url 'user:login' %}" >
        {% csrf_token %}
       
        <div class="bg-grey-lighter min-h-screen flex flex-col">
            <div class="container max-w-sm mx-auto flex-1 flex flex-col items-center justify-center px-2">
                <div class="bg-white px-6 py-8 rounded shadow-md text-black w-full">
                    <h1 class="mb-8 text-3xl text-center">Sign In</h1>

                    <input
                            type="email"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="email"
                            placeholder="Email" />
                    
                    <input
                            type="password"
                            class="block border border-grey-light w-full p-3 rounded mb-4"
                            name="password"
                            placeholder="Password" />
                    <button
                            type="submit"
                            class="text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded "
                    >LogIn</button>

                </div>

                <div class="text-grey-dark mt-6">
                    Don't have an account?
                    <a class="no-underline border-b border-blue" href="{%url 'user:signup' %}">
                        <span class="text-blue">Sign Up</span>
                    </a>.
                </div>
            </div>
        </div>
    </form> -->
    <div class="container" >
    <div class="signup-form" style="margin:auto">
        <form class="form-horizontal" method="POST" action="{% url 'user:login' %}" >
            {% csrf_token %}              
            <div class="row">
                <div class="col-8 offset-4">
                    <h2>Login</h2>
                </div>	
              </div>	
            <div class="form-group row">
                <label class="col-form-label col-4">Email Address</label>
                <div class="col-8">
                    <input type="email" class="form-control" name="email" required="required" placeholder="Email">
                </div>        	
            </div>
            <div class="form-group row">
                <label class="col-form-label col-4">Password</label>
                <div class="col-8">
                    <input type="password" class="form-control" name="password" required="required"  placeholder="Password">
                </div>        	
            </div>
            <div class="form-group row">
                <div class="col-8 offset-4">
                    <button type="submit" class="btn btn-primary btn-lg">Login</button>
                </div>  
            </div>		      
        </form>
        <div class="text-center" style="color:white;">Not yet Registered? <a href="{%url 'user:signup' %}">Register here</a></div>
    </div>
</div>
{% endblock %}

labt/user/templates/user/profile.html
{% extends 'user/base.html' %}

{% block content %}
{% load static %}
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

       
    <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 600px; background-image: url(../../../static/base/top.png); background-size: cover; background-position: center bottom;">
        <!-- <span class="mask bg-gradient-default opacity-8"></span> -->
        <div class="container-fluid d-flex align-items-center">
            <div class="row">
                <div class="col-lg-10 col-md-12">
                    <h1 class="display-2 text-white">Hello,<br> {{first_name}} {{last_name}}</h1>
                    <!-- <div  style="background-color: black;">
                    <p class="text-white mt-0 mb-5" style="font-size: 2rem; font-weight: bolder;">This is your profile page. You can Update your 
                        Profile as you wish. You can also see your trip statistics
                    </p>
                    </div> -->
                    <!-- {# <a href="#!" class="btn btn-info">Edit profile</a>#} -->
                </div>

            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
                <div class="card card-profile shadow">
                    <div class="card-body pt-0 pt-md-4">
                        <div class="text-center">
                            <h3>
                                <!-- {{ first_name }} {{ last_name }}<span class="font-weight-light">, 27</span> -->
                                Extra Stats
                            </h3>
                            
                        </div>
                        <!-- <br>
                        <br>
                        <div >
                            <h4>Ongoing Trips:</h4>
                            <h4>Upcoming Trips: </h4>
                            <h4>Past Trips: </h4>
                            <br><br>
                            <h4>Congrats! You have added Trips to your Travlog account.</h4>
                        </div> -->
                    </div>
                </div>
            </div>
            <div class="col-xl-8 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-body">
                        <form class="" method="POST" action="{% url 'user:profile' %}" >
                            {% csrf_token %}
                            <div class="card-header bg-white border-0">
                                <div class="row align-items-center">
                                    <div class="col-8">
                                        <h3 class="mb-0">My account</h3>
                                    </div>
                                    <div class="col-4 text-right">
                                        <button type = "submit" class="btn btn-sm btn-success">Update
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <br>
                            <h4 class="text-muted mb-4">User Information</h4>


                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-username">First Name</label>
                                            <input type="text" id="input-username" class="form-control form-control-alternative" placeholder="First name" value="{{first_name}}" name = "first_name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-last-name">Last name</label>
                                            <input type="text" id="input-last-name" class="form-control form-control-alternative" placeholder="Last name" value="{{last_name}}" name = "last_name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="form-control-label" for="input-email">Email address</label>
                                            <input type="email" id="input-email" class="form-control form-control-alternative" placeholder="email" value = "{{email}}" name = "email">
                                        </div>
                                    </div>
                                    
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-gender">Gender</label>
                                            <input type="text" id="input-gender" class="form-control form-control-alternative" value="{{gender}}" disabled>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-dob">Date of Birth</label>
                                            <input type="text" id="input-dob" class="form-control form-control-alternative" value="{{dob}}" disabled>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4">
                            <h4 class="text-muted mb-4">Contact Information</h4>
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-address">Address</label>
                                            <input id="input-address" class="form-control form-control-alternative" placeholder="Home Address" value="{{address}}" type="text" name = "address">
                                        </div>
                                    </div>
                                    <div class="col-lg-4">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-mobile">Mobile</label>
                                            <input type="text" id="input-mobile" class="form-control form-control-alternative" placeholder="Mobile No." value="{{mobile}}" name = "mobile">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <hr class="my-4">
                            <h4 class="text-muted mb-4">Security Information</h4>
                            <div class="pl-lg-4">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-password">Current Password</label>
                                            <input type="password" id="input-password" class="form-control form-control-alternative" value="{{curr_password}}" name="curr_password">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-password">New Password </label>
                                            <input type="password" id="input-password" class="form-control form-control-alternative" value="" name="new_password">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group focused">
                                            <label class="form-control-label" for="input-password">Confirm New Password </label>
                                            <input type="password" id="input-password" class="form-control form-control-alternative" value="" name="confirm_password">
                                        </div>
                                    </div>
                                </div>
                            </div>
                            

                            <div class="pl-lg-4">
                                <div class="row">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

    

{% endblock %}